### ISSUE TITLE
Error:Failure determining what xinput1_3.Ordinal95+28 means

### ISSUE THREAD

**Issue by Mxnority** [HackerHansen/AmongUs-Cosmetics-Unlocker#1]
![image](https://user-images.githubusercontent.com/45408633/113344451-b4ed6900-92f6-11eb-9a39-b789ba061147.png)

**Comment by HackerHansen** [comment]
Are you using a cracked version of Among Us?

**Comment by Mxnority** [comment]
![image](https://user-images.githubusercontent.com/45408633/113345461-19f58e80-92f8-11eb-864a-929519a432a2.png)
No sir

**Comment by HackerHansen** [comment]
Try relaunching the game, I'm not sure what the problem is, sorry. I'll close this issue for now.
